bugfix: don't depend on cPickle-specific behavion
Passing None as the 'file' parameter of pickle.dump() throws
`AttributeError: 'NoneType' object has no attribute 'write'`.